Fixed issue with environ on older Macs
libzygote.dylib wasn't building correctly due to the following error
(thanks to @roks):

    cc -o libzygote.dylib -dynamiclib zygote.o -ldl
    Undefined symbols for architecture x86_64:
     "_environ", referenced from:
         _grow_this_zygote in zygote.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [libzygote.dylib] Error 1

The Macs had the following versions:

    Target: i686-apple-darwin10
    gcc version 4.2.1 (Apple Inc. build 5666) (dot 3)

    Target: i686-apple-darwin11
    gcc version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)

Changing the `environ` declaration for Mac OS X according to the man
page fixed the error.